# Generated by Django 3.0.8 on 2020-11-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='img8.png', upload_to='images'),
        ),
    ]
